import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({ children }) {
  return (
    <div className={
      "min-h-screen  max-w-[1500px] mx-auto flex flex-col gap-10 bg-bgBase "
    }>

      <Header />
      {children}
      <Footer />
    </div>
  );
}
