import "./globals.css";
import StoreProvider from "@/stores/StoreProvider";
import { store } from "@/stores/store";
import { login } from "@/stores/userSlice";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await store.dispatch(login({ id: 1, name: "Dirk or Rick" }));
  const user = await store.getState().user;

  return (
    <html lang="en">
      <body className={"min-h-screen flex flex-col justify-between "}>
        <StoreProvider
          preloadedState={{
            user,
          }}
        >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
